import "dotenv/config";
import "dotenv-expand/config";

export default {
    "camelCase": false,
    "customImports": {},
    "dateParser": "timestamp",
    "defaultSchemas": [process.env.SOCIAL_DATABASE_NAME],
    "dialect": null,
    "domains": true,
    "envFile": null,
    "excludePattern": null,
    "includePattern": `${process.env.SOCIAL_DATABASE_NAME}.+(documents|lms_provider_learning|lms_provider_learning_moduli|lms_provider_learning_scorm|lms_category)`,
    "logLevel": "warn",
    "numericParser": "string",
    "outFile": "./node_modules/kysely-codegen/dist/db.d.ts",
    "overrides": {},
    "partitions": false,
    "print": false,
    "runtimeEnums": false,
    "singularize": false,
    "skipAutogeneratedFileComment": false,
    "typeMapping": {},
    "typeOnlyImports": true,
    "url": `${process.env.SOCIAL_DATABASE_URL}`,
    "verify": false
  }